# Site settings
title: Biagio Carrella's CV 
description: bcarrella's CV
favicon: /assets/img/avatar.JPG
baseurl: http://bcarrella.github.io/resumecard/
url: http://bcarrella.github.io/resumecard/
rss_url: /pages/atom.xml
google_analytics: UA-5243448-5
cv_url: /assets/CV-Europass-20181228-Carrella-IT.pdf

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Biagio Carrella
  title: ICT Specialist
  address: Napoli, Italy
  email: mail(at)biagiocarrella.it
  link: http://www.biagiocarrella.it
  weibo:
  github: bcarrella
  linkedin: bcarrella
  twitter: bcarrella
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Banca D'Italia
      location: Roma, Italy
      title: System Engineer
      started: 2017
      duration: (2017 - Present)
      description: Service asset and configuration management using IBM Tivoli Application Dependency Discovery Manager and IBM Smart Control Desk (Maximo) Asset Management.
    - work2:
      company: 3F & Edin S.p.A.
      location: Napoli, Italy
      title: Software Developer
      started: 2007
      duration: (2007 - 2017)
      description: Application Developer, Database Administrator in a wide variety of business applications. Particularly interested in client/server and relational database design using MySQL. Advanced CAD and geometrical application developer.
    - work3:
      company: Lutech S.p.A.
      location: Milano, Italy
      title: System Engineer
      started: 2006
      duration: (2006 - 2006)
      description:  Internship on Genesys Framework for Computer Telephony Integration
  educationHistory:
    - education1:
      organization: Università di Salerno
      location: Fisciano, Italy
      degree: Bachelor
      major: Computer Science
      started: 2001
      duration: (2001 - 2005)
      description: Bachelor’s degree in Computer Science 99/110 graduation
  languages:
    - language1:
      name: Italian
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: French
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: C/C++
      percentage: 100%
    - skill2:
      name: SQL
      percentage: 100%
    - skill3:
      name: JavaScript
      percentage: 80%
    - skill4:
      name: AngularJS
      percentage: 50%
    - skill5:
      name: PHP
      percentage: 50%
    - skill6:
      name: Python
      percentage: 50%
    - skill7:
      name: Java/Java EE
      percentage: 90%
    - skill8:
      name: HTML
      percentage: 90%
